version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/pip"
    schedule:
      interval: "weekly"
    assignees:
      - "AbstractUmbra"

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "AbstractUmbra"
